package m2_proyecto;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.*; // Este paquete contiene LocalDate, LocalTime y LocalDateTime.
import java.util.Date;

/**
 * Universidad Tecnologica de la Huasteca Hidalguiense
 * TSU En Tecnologias de la Informacion Area Desarrollo de Software Multiplataforma
 * @author Irving Aldahir Angeles Romero
 * Estructura de Datos Aplicadas
 * Clase: FrmGestPrestamo
 * Fecha: 28 oct 2024
 */
public class FrmGestPrestamo extends javax.swing.JFrame {
    static TDAArregloLibreria1D coleccionLibros;
    TDAArregloPrestamos2D prestamos;
    static TDAListaLigada lista;

    public FrmGestPrestamo(TDAArregloLibreria1D coleccionLibros, TDAListaLigada lista) {
        this.coleccionLibros = coleccionLibros;
        this.lista = lista;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        // Inicializar la colección de préstamos
        this.prestamos = new TDAArregloPrestamos2D();

        // Llenar el ComboBox al inicializar el formulario
        llenarComboBoxLibros();
    }

    private void llenarComboBoxLibros() {
        cmbLibroPrestar.removeAllItems(); //Limpiar lista
        Libro[] libros = coleccionLibros.cargarLibrosDesdeListaLigada();
        for(int l=0; l<libros.length;l++){
           cmbLibroPrestar.addItem(l+1 +".- "+ libros[l].getTitulo());                
        }
    txtFechaPrestamo.setText(LocalDate.now().toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbHistorialPrestamos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbLibroPrestar = new javax.swing.JComboBox<>();
        btnDevuelto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrestamos = new javax.swing.JTextArea();
        btnReiniciarPrestamos = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lblLibroMasPrestado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFechaPrestamo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFechaLimite = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Gestion de Prestamos");

        jLabel13.setText("libro a prestar");
        jLabel13.setToolTipText("");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Id Usuario:");

        jLabel14.setText("Historial de prestamos del usuario");

        btnDevuelto.setText("Marcar como devuelto");
        btnDevuelto.setToolTipText("");
        btnDevuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevueltoActionPerformed(evt);
            }
        });

        jLabel15.setText("Todos los prestamos");

        txtPrestamos.setColumns(20);
        txtPrestamos.setRows(5);
        jScrollPane1.setViewportView(txtPrestamos);

        btnReiniciarPrestamos.setText("reinicializar prestamos");
        btnReiniciarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarPrestamosActionPerformed(evt);
            }
        });

        btnPrestar.setText("prestar libro");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Libro mas prestado: ");

        lblLibroMasPrestado.setText("libro");

        jLabel16.setText("fecha");

        jLabel7.setText("fecha limite");

        jLabel8.setText("fecha Inicio");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Irving Aldahir Angeles Romero. - ProyM2.");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addComponent(txtNombreUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbHistorialPrestamos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbLibroPrestar, javax.swing.GroupLayout.Alignment.LEADING, 0, 262, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaPrestamo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaLimite)))
                    .addComponent(btnReiniciarPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(172, 172, 172)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLibroMasPrestado)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLibroPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevuelto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbHistorialPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrestar)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(lblLibroMasPrestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciarPrestamos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //los metodos se encuentran en la clase Prestamos2D
    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        //este boton registrara el prestamo en Prestamos2D prestamos; una vez registrado el prestamo se quitara ese libro del cmbLibroPrestar ya que ese libro ya esta prestado a menos que exista mas de 1 ejemplar, mostrara el prestamo en el historial de prestamos del usuario en el cmbHistorialPrestamos, y tambien ira listando todos los prestamos realizados en el txtPrestamos, cada que se haga un prestamo se actualizara cual es el libro mas prestado y se mostrara en el lblLibroMasPrestado
        String libroSeleccionado = (String) cmbLibroPrestar.getSelectedItem();
        String usuario = txtNombreUsuario.getText(); 
        String fechaPrestamo = txtFechaPrestamo.getText();
        String idUsuario = txtIdUsuario.getText();
        
        String numExistente = "\\d+\\.- ";
        
        // Reemplazar el patrón por una cadena vacía (eliminación)
        String resultado = libroSeleccionado.replaceAll(numExistente, "");
        
        Libro libro = coleccionLibros.obtenerLibro(resultado);

        if (prestamos.obtenerDisponibilidadLibro(libro)) {
            prestamos.registrarPrestamo(libro, usuario, fechaPrestamo,idUsuario);
            // Actualizar el ComboBox para quitar el libro prestado
            cmbLibroPrestar.removeItem(libroSeleccionado);
            // Agregar el préstamo al historial
            cmbHistorialPrestamos.addItem(libro.getTitulo() + " - " + fechaPrestamo );
            // Actualizar el texto del área de préstamos
            txtPrestamos.append("Libro:" + libro.getTitulo() + "; Usuario:" + usuario + "; Fecha:" + fechaPrestamo + "\n");
            // Calcular y mostrar el libro más prestado
            Libro libroMasPrestado = prestamos.calcularLibroMasPrestado();
            lblLibroMasPrestado.setText(libroMasPrestado != null ? libroMasPrestado.getTitulo() : "");
        } else {
            JOptionPane.showMessageDialog(this, "El libro no está disponible para préstamo.");
        }
    }//GEN-LAST:event_btnPrestarActionPerformed


    private void btnDevueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevueltoActionPerformed
    
        try{
        String libroSeleccionado = (String) cmbHistorialPrestamos.getSelectedItem();
        if (libroSeleccionado == null || libroSeleccionado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un libro del historial de préstamos.");
            return;
        }

        String tituloLibro = libroSeleccionado.split(" - ")[0];
        String nombreUsuario = txtNombreUsuario.getText();
        String idUsuario = txtIdUsuario.getText();
        String fecha = txtFechaPrestamo.getText();

        // Verificar si el préstamo existe en Prestamos2D
        if (prestamos.existePrestamo(tituloLibro, fecha, idUsuario,nombreUsuario)) {
            Libro libro = coleccionLibros.obtenerLibro(tituloLibro);
            if (libro != null) {
                prestamos.registrarDevolucion(libro, nombreUsuario);
                cmbLibroPrestar.addItem(libro.getTitulo());
                actualizarHistorialYTextoPrestamos();
                JOptionPane.showMessageDialog(this, "Libro devuelto con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el libro en la colección.");
            }
        }    
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Verifica los datos de entrada.");
        }

    }//GEN-LAST:event_btnDevueltoActionPerformed

    private void btnReiniciarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarPrestamosActionPerformed
        //este boton borrara todos los prestamos de Prestamos2D prestamos; y actualizara  el cmbHistorialPrestamos y txtPrestamos
        prestamos.reiniciarPrestamos();
        actualizarHistorialYTextoPrestamos();
        txtNombreUsuario.setText("");
        txtIdUsuario.setText("");
        txtFechaPrestamo.setText("");
        cmbHistorialPrestamos.setSelectedItem("");
    JOptionPane.showMessageDialog(this, "Todos los préstamos han sido reiniciados.");    }//GEN-LAST:event_btnReiniciarPrestamosActionPerformed
    
    private void actualizarHistorialYTextoPrestamos() {
        cmbHistorialPrestamos.removeAllItems();
        txtPrestamos.setText(""); // Limpiar el área de texto
        for (Libro libro : coleccionLibros.cargarLibrosDesdeListaLigada()) {
            if (!prestamos.obtenerDisponibilidadLibro(libro)) {
                cmbHistorialPrestamos.addItem(libro.getTitulo());
                txtPrestamos.append("Prestado: " + libro.getTitulo() + "\n");
            }
        }
    }   
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            dispose(); // Cierra solo este formulario
    }//GEN-LAST:event_formWindowClosing

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    //En este boton buscara los prestamos que existan entre esas fechas y los mostrarara en el txtPrestamos
    String fechaInicio = txtFechaInicio.getText();
    String fechaFin = txtFechaLimite.getText();
    Date fechaInicioDate = convertirCadenaADate(fechaInicio);
    Date fechaFinDate = convertirCadenaADate(fechaFin);

    if (fechaInicioDate == null || fechaFinDate == null) {
        JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use yyyy-MM-dd.");
        return; // Salir si hubo un error
    }

    Libro[] librosEncontrados = prestamos.librosPrestadosEnRangosDeFechas(fechaInicio, fechaFin);

    txtPrestamos.setText("");

    if (librosEncontrados.length == 0) {
        txtPrestamos.setText("No se encontraron préstamos en este rango de fechas.");
    } else {
        // Formatear y mostrar los libros en el área de texto
        StringBuilder resultados = new StringBuilder("Libros prestados entre " + fechaInicio + " y " + fechaFin + ":\n\n");
        for (Libro libro : librosEncontrados) {
            resultados.append(libro).append("\n"); // Asegúrate de que el método getTitulo() esté implementado
        }
        txtPrestamos.setText(resultados.toString());
    }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private static Date convertirCadenaADate(String fecha) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = null;
        try {
            date = sdf.parse(fecha); // Convertir la cadena a Date
        } catch (Exception e) {
            e.printStackTrace(); // Manejar excepciones en caso de un error de formato
        }
        return date; // Devolver el objeto Date
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestPrestamo(coleccionLibros,lista).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevuelto;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnReiniciarPrestamos;
    private javax.swing.JComboBox<String> cmbHistorialPrestamos;
    private javax.swing.JComboBox<String> cmbLibroPrestar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLibroMasPrestado;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtFechaLimite;
    private javax.swing.JTextField txtFechaPrestamo;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextArea txtPrestamos;
    // End of variables declaration//GEN-END:variables

}
